import {
  compileErrors,
  dereference,
  parse as parseOpenAPIDocument,
  validate,
} from "@readme/openapi-parser"
import type { ParserOptions, ValidationResult } from "@readme/openapi-parser"
import { Buffer } from "buffer"
import YAML from "yaml"
import type {
  OpenAPISpec,
  Parameter,
  ParsedRoute,
  SchemaObject,
  ServerObject,
} from "./types"
import { isExternalRefAllowed, originOf } from "./url-guard"

export const HTTP_METHODS = ["get", "post", "put", "patch", "delete", "head", "options"] as const
export type HttpMethod = (typeof HTTP_METHODS)[number]

const globalScope = globalThis as typeof globalThis & { Buffer?: typeof Buffer }
globalScope.Buffer ??= Buffer

// Origins an untrusted spec is allowed to pull external $ref from: the app's own
// origin plus the origin the spec itself was loaded from. Everything else (other
// hosts, internal/private addresses, non-http schemes) is refused.
function computeAllowedOrigins(sourceUrl?: string): string[] {
  const origins = new Set<string>()
  if (typeof location !== "undefined" && location.origin && location.origin !== "null") {
    origins.add(location.origin)
  }
  if (sourceUrl) {
    const o = originOf(sourceUrl)
    if (o) origins.add(o)
  }
  return [...origins]
}

// Build parser options whose http resolver vets every external $ref. Disallowed
// refs are degraded to an empty schema (no request issued) and recorded in
// `blocked`; the library's built-in unsafe-URL guard is a no-op in browsers, so
// this is the actual SSRF defense.
function buildParserOptions(allowedOrigins: string[], blocked: Set<string>): ParserOptions {
  // @readme's ParserOptions only types `http.timeout`, but it forwards the full
  // resolve config to @apidevtools/json-schema-ref-parser, whose http resolver
  // honors canRead/read. Extracted to a variable so the literal excess-property
  // check doesn't reject the (runtime-valid) canRead/read fields.
  const httpResolver: { timeout?: number; canRead: RegExp; read: (file: { url: string }) => Promise<string> } = {
    canRead: /^https?:\/\//i,
    async read(file: { url: string }): Promise<string> {
      if (!isExternalRefAllowed(file.url, allowedOrigins)) {
        blocked.add(file.url)
        return "{}"
      }
      const res = await fetch(file.url)
      if (!res.ok) {
        throw new Error(`Failed to fetch external $ref ${file.url}: ${res.status}`)
      }
      return await res.text()
    },
  }
  return {
    dereference: {
      circular: "ignore",
    },
    resolve: {
      external: true,
      file: false,
      http: httpResolver,
    },
  } satisfies ParserOptions
}

type ParserInput = Parameters<typeof parseOpenAPIDocument>[0]

function asParserInput(input: string | OpenAPISpec): ParserInput {
  return input as ParserInput
}

function cloneSpec<T>(spec: T): T {
  return structuredClone(spec)
}

export function getErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}

function formatValidationError(result: ValidationResult): string {
  if (result.valid) return ""
  return compileErrors(result).trim()
    || result.errors[0]?.message
    || "Invalid OpenAPI document"
}

export function parseSpecText(text: string): OpenAPISpec {
  const trimmed = text.trim()
  if (trimmed.startsWith("{")) {
    return JSON.parse(trimmed) as OpenAPISpec
  }
  return YAML.parse(trimmed) as OpenAPISpec
}

export function sanitizeNonStandardExtensions(spec: OpenAPISpec): { spec: OpenAPISpec; warnings: string[] } {
  const result = cloneSpec(spec)
  const warnings: string[] = []

  for (const [path, pathItem] of Object.entries(result.paths || {})) {
    for (const method of HTTP_METHODS) {
      const op = pathItem[method]
      if (!op?.responses) continue
      for (const [status, response] of Object.entries(op.responses)) {
        if (!response.content) continue
        for (const [contentType, media] of Object.entries(response.content)) {
          if (media.itemSchema && !media.schema) {
            media.schema = media.itemSchema
            delete media.itemSchema
            warnings.push(
              `Non-standard property "itemSchema" at paths.${path}.${method}.responses.${status}.content["${contentType}"]. `
              + `This is a draft proposal (not part of OpenAPI 3.1.0) commonly generated by FastAPI/sse-starlette for SSE endpoints. `
              + `Converted to "schema" for compatibility.`,
            )
          }
        }
      }
    }
  }

  return { spec: result, warnings }
}

// After dereferencing with circular:"ignore", circular references remain as
// literal { $ref } nodes. Tag them with _circular so format-schema / SchemaTree
// can render "[circular]" and example generation can prune them (the marker the
// types.ts comment always promised but nothing ever set).
function markCircularRefs(root: unknown): void {
  const seen = new WeakSet<object>()
  const walk = (node: unknown): void => {
    if (!node || typeof node !== "object" || seen.has(node)) return
    seen.add(node)
    if (Array.isArray(node)) {
      node.forEach(walk)
      return
    }
    const obj = node as Record<string, unknown>
    if (typeof obj.$ref === "string" && obj._circular === undefined) {
      obj._circular = obj.$ref
    }
    for (const v of Object.values(obj)) walk(v)
  }
  walk(root)
}

export async function parseValidatedSpec(
  input: string | OpenAPISpec,
  opts: { sourceUrl?: string } = {},
): Promise<{
  spec: OpenAPISpec
  sourceSpec: OpenAPISpec
  warnings: string[]
}> {
  const blocked = new Set<string>()
  const parserOptions = buildParserOptions(computeAllowedOrigins(opts.sourceUrl), blocked)

  const parserInput = asParserInput(input)
  const sourceSpec = await parseOpenAPIDocument(parserInput, parserOptions) as OpenAPISpec

  // Sanitize non-standard properties before validation
  const { spec: sanitizedSource, warnings } = sanitizeNonStandardExtensions(sourceSpec)

  const validationInput = asParserInput(cloneSpec(sanitizedSource))
  const validation = await validate(validationInput, parserOptions)
  if (!validation.valid) {
    throw new Error(formatValidationError(validation))
  }

  const dereferenceInput = asParserInput(cloneSpec(sanitizedSource))
  const spec = await dereference(dereferenceInput, parserOptions)
  markCircularRefs(spec)

  if (blocked.size > 0) {
    const sample = [...blocked].slice(0, 5).join(", ")
    warnings.push(
      `Blocked ${blocked.size} external $ref pointer(s) targeting untrusted or internal URLs `
      + `(SSRF protection): ${sample}${blocked.size > 5 ? ", …" : ""}. These were replaced with empty schemas.`,
    )
  }

  return {
    spec: spec as OpenAPISpec,
    sourceSpec: sourceSpec as OpenAPISpec,
    warnings,
  }
}

export function resolveServerUrl(srv: ServerObject): string {
  let url = srv.url
  if (srv.variables) {
    for (const [k, v] of Object.entries(srv.variables)) {
      url = url.replace(`{${k}}`, v.default || "")
    }
  }
  return url
}

function rewriteRefs(obj: unknown): void {
  if (!obj || typeof obj !== "object") return
  if (Array.isArray(obj)) {
    obj.forEach(rewriteRefs)
    return
  }
  const r = obj as Record<string, unknown>
  if (typeof r.$ref === "string" && r.$ref.startsWith("#/definitions/")) {
    r.$ref = r.$ref.replace("#/definitions/", "#/components/schemas/")
  }
  for (const v of Object.values(r)) rewriteRefs(v)
}

function schemaFromSwaggerParameter(param: Parameter): SchemaObject {
  if (param.type === "file") {
    return {
      type: "string",
      format: "binary",
      description: param.description || "",
    }
  }

  const schema: SchemaObject = { type: param.type || "string" }
  if (param.format) schema.format = param.format
  if (param.enum) schema.enum = param.enum
  if (param.default !== undefined) schema.default = param.default
  if (param.description) schema.description = param.description
  return schema
}

export function convertSwaggerV2(spec: OpenAPISpec): OpenAPISpec {
  const s = cloneSpec(spec)
  const scheme = s.schemes?.[0] || "https"
  const host = s.host || ""
  const basePath = (s.basePath || "").replace(/\/$/, "")
  if (host) s.servers = [{ url: `${scheme}://${host}${basePath}` }]

  if (s.definitions && !s.components) {
    s.components = { schemas: s.definitions }
    rewriteRefs(s.paths)
    rewriteRefs(s.components)
  }
  if (s.securityDefinitions) {
    if (!s.components) s.components = {}
    // Convert Swagger 2.0 top-level oauth2 fields to OAS3 flows structure
    for (const scheme of Object.values(s.securityDefinitions)) {
      if (scheme.type === "oauth2" && scheme.flow && !scheme.flows) {
        const flowObj = {
          tokenUrl: scheme.tokenUrl,
          authorizationUrl: scheme.authorizationUrl,
          scopes: scheme.scopes ?? {},
        }
        const flowMap: Record<string, string> = {
          password: "password",
          application: "clientCredentials",
          accessCode: "authorizationCode",
          implicit: "implicit",
        }
        const oas3Flow = flowMap[scheme.flow]
        if (oas3Flow) {
          scheme.flows = { [oas3Flow]: flowObj }
        }
      }
    }
    s.components.securitySchemes = s.securityDefinitions
  }

  const globalConsumes = s.consumes || ["application/json"]
  for (const pathItem of Object.values(s.paths || {})) {
    for (const method of HTTP_METHODS) {
      const op = pathItem[method]
      if (!op) continue
      const params = op.parameters || []
      const bodyParam = params.find(p => p.in === "body")
      const formParams = params.filter(p => p.in === "formData")
      const consumes = op.consumes || globalConsumes
      op.parameters = params.filter(p => p.in !== "body" && p.in !== "formData")

      if (bodyParam && !op.requestBody) {
        op.requestBody = {
          required: !!bodyParam.required,
          content: {
            [consumes[0] || "application/json"]: {
              schema: bodyParam.schema || {},
            },
          },
        }
      } else if (formParams.length && !op.requestBody) {
        const isFile = formParams.some(p => p.type === "file")
        const ct = isFile
          ? "multipart/form-data"
          : consumes.includes("multipart/form-data")
            ? "multipart/form-data"
            : "application/x-www-form-urlencoded"
        const props: Record<string, SchemaObject> = {}
        const req: string[] = []
        for (const fp of formParams) {
          props[fp.name] = schemaFromSwaggerParameter(fp)
          if (fp.required) req.push(fp.name)
        }
        const schema: SchemaObject = { type: "object", properties: props }
        if (req.length) schema.required = req
        op.requestBody = { content: { [ct]: { schema } } }
      }

      const produces = op.produces || s.produces || ["application/json"]
      for (const resp of Object.values(op.responses || {})) {
        if (resp.schema && !resp.content) {
          resp.content = { [produces[0] || "application/json"]: { schema: resp.schema } }
          delete resp.schema
        }
      }
    }
  }
  return s
}

export function normalizeParsedSpec(spec: OpenAPISpec): OpenAPISpec {
  return spec.swagger === "2.0" ? convertSwaggerV2(spec) : spec
}

export function getOperationKey(method: string, path: string): string {
  return `${method.toUpperCase()} ${path}`
}

export function collectModelRefs(obj: unknown, found: Set<string>): void {
  if (!obj || typeof obj !== "object") return
  const record = obj as Record<string, unknown>
  if (typeof record.$ref === "string") {
    const match = record.$ref.match(/^#\/(components\/schemas|definitions)\/(.+)$/)
    const modelName = match?.[2]
    if (modelName) found.add(modelName)
  }
  if (Array.isArray(obj)) {
    for (const item of obj) collectModelRefs(item, found)
  } else {
    for (const v of Object.values(record)) collectModelRefs(v, found)
  }
}

export function buildModelRouteMap(routes: ParsedRoute[]) {
  const modelToRoutes: Record<string, number[]> = {}
  const routeToModels: Record<number, string[]> = {}
  for (const [i, route] of routes.entries()) {
    const models = route.referencedModels
    routeToModels[i] = models
    for (const m of models) {
      if (!modelToRoutes[m]) modelToRoutes[m] = []
      modelToRoutes[m].push(i)
    }
  }
  return { modelToRoutes, routeToModels }
}
